language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
  - nightly
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-nightly
before_script: composer install
script: vendor/bin/phpspec run
